name: Dev Branch Deployment

on:
  push:
    branches:
      - patch

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: saathiproject/saathi-uploader:latest
          build-args: |
            "SENTRY_DSN=${{ secrets.SENTRY_DSN }}"
            "UPLOAD_API_URL=${{ secrets.UPLOAD_API_URL }}"
